// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContractUIClient is the client API for ContractUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractUIClient interface {
	// ListEngineSpecs returns a list of Contract Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ContractUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type contractUIClient struct {
	cc grpc.ClientConnInterface
}

func NewContractUIClient(cc grpc.ClientConnInterface) ContractUIClient {
	return &contractUIClient{cc}
}

func (c *contractUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ContractUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContractUI_ServiceDesc.Streams[0], "/v1.ContractUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &contractUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContractUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type contractUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *contractUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *contractUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ContractUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractUIServer is the server API for ContractUI service.
// All implementations must embed UnimplementedContractUIServer
// for forward compatibility
type ContractUIServer interface {
	// ListEngineSpecs returns a list of Contract Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ContractUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedContractUIServer()
}

// UnimplementedContractUIServer must be embedded to have forward compatible implementations.
type UnimplementedContractUIServer struct {
}

func (UnimplementedContractUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ContractUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedContractUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedContractUIServer) mustEmbedUnimplementedContractUIServer() {}

// UnsafeContractUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractUIServer will
// result in compilation errors.
type UnsafeContractUIServer interface {
	mustEmbedUnimplementedContractUIServer()
}

func RegisterContractUIServer(s grpc.ServiceRegistrar, srv ContractUIServer) {
	s.RegisterService(&ContractUI_ServiceDesc, srv)
}

func _ContractUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContractUIServer).ListEngineSpecs(m, &contractUIListEngineSpecsServer{stream})
}

type ContractUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type contractUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *contractUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ContractUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ContractUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractUI_ServiceDesc is the grpc.ServiceDesc for ContractUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ContractUI",
	HandlerType: (*ContractUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ContractUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ContractUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "contract-ui.proto",
}
